feat: migrate zf2-google-analytics to mot-google-analytics
dvsa/mot-google-analytics pull request #1
Opened 2023-06-07 14:26 UTC by caoimheb

## Description

Migrate zf2-google-analytics to mot-google-analytics

Related issue: [BL-14411](https://dvsa.atlassian.net/browse/BL-14411)

## Before submitting (or marking as "ready for review")

- [x] Does the pull request title follow the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) specification?
- [x] Have you performed a self-review of the code
- [ ] Have you have added tests that prove the fix or feature is effective and working
- [ ] Did you make sure to update any documentation relating to this change?

2023-06-08 16:05 UTC, faggc approved these changes

2023-06-12 09:15 UTC, jennifer-choo requested changes

2023-06-12 09:15 UTC, jennifer-choo commented on README.md
> +Contributing
```suggestion
## Contributing
```
Would you be able to change this? Just to make things consistent

2023-06-12 09:23 UTC, jennifer-choo approved these changes

2023-06-13 08:51 UTC, merged